---
# tasks file for deployworkspaces
#- name: whoami
#  shell: whoami

- name: Create workspaces directory if it does not exist
  file:
    path: /home/ec2-user/workspaces
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create bin directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create payload directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin/payload
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: pull csv file from s3-bucket
  command: aws s3 cp s3://qcentrix.createworkspaces/create-workspaces-nick.csv /home/ec2-user/workspaces/bin/create-workspaces.csv
  remote_user: ec2-user

  #- name: pull awscli script file from role
  #  copy:
  #    src: "{{ role_path }}/files/awscli.sh"
  #    dest: /home/ec2-user/workspaces/bin/awscli.sh
  #    mode: '0777'
  #    owner: ec2-user
  #    group: ec2-user

- name: pull python script file from role
  copy:
    src: "{{ role_path }}/files/csvconverter.py"
    dest: /home/ec2-user/workspaces/bin/csvconverter.py
    mode: '0777'
    owner: ec2-user
    group: ec2-user

- name: pull bash script file from role
  copy:
    src: "{{ role_path }}/files/create-batchworkspaces.sh"
    dest: /home/ec2-user/workspaces/bin/create-batchworkspaces.sh
    mode: '0777'
    owner: ec2-user
    group: ec2-user

    #- name: download from s3
    #  script: "{{ role_path }}/files/awscli.sh"
  #    remote_src: True

- name: parse csv into json payload(s)
  script: "{{ role_path }}/files/csvconverter.py create-workspaces.csv"
  args:
    executable: python3
    #  remote_src: True

- name: parse csv into json payload(s)
  script: /home/ec2-user/workspaces/bin/create-batchworkspaces.sh
  #  remote_src: True

- name: running batch workspaces deploy process
  script: create-batchworkspaces.sh
  #  remote_src: True

- name: cleanup of artifacts
  file:
    path: /home/ec2-user/workspaces/
    state: absent
