---
# tasks file for deployworkspaces

- name: install python3
  command: amazon-linux-extras install python3 -y
  become: yes

- name: Create workspaces directory if it does not exist
  file:
    path: /home/ec2-user/workspaces
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create bin directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create payload directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin/payload
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: pull csv file from s3-bucket
  command: aws s3 cp s3://qcentrix.createworkspaces/create-workspaces.csv /home/ec2-user/workspaces/bin/create-workspaces.csv
  remote_user: ec2-user

- name: pull parser python script file from role
  copy:
    src: "{{ role_path }}/files/csvconverter.py"
    dest: /home/ec2-user/workspaces/bin/csvconverter.py
    mode: '0777'
    owner: ec2-user
    group: ec2-user

#- name: pull email python script file from role
#  copy:
#    src: "{{ role_path }}/files/senddeployemail.py"
#    dest: /home/ec2-user/workspaces/bin/senddeployemail.py
#    mode: '0777'
#    owner: ec2-user
#    group: ec2-user

- name: pull bash script file from role
  copy:
    src: "{{ role_path }}/files/create-batchworkspaces.sh"
    dest: /home/ec2-user/workspaces/bin/create-batchworkspaces.sh
    mode: '0777'
    owner: ec2-user
    group: ec2-user

- name: parse csv into json payload(s)
  command: python3 csvconverter.py create-workspaces.csv
  args:
    chdir: /home/ec2-user/workspaces/bin/

- name: running batch workspaces deploy process
  command: bash create-batchworkspaces.sh
  remote_user: ec2-user
  args:
    chdir: /home/ec2-user/workspaces/bin/

- name: cleanup of artifacts
  file:
    path: /home/ec2-user/workspaces/bin/payload
    state: absent

- name: archive csv file in s3-bucket
  command: 'aws s3 cp s3://qcentrix.createworkspaces/create-workspaces.csv s3://qcentrix.createworkspaces/archive/{{ ansible_date_time.iso8601_basic_short }}create-workspaces-archive.csv'
  remote_user: ec2-user
  ignore_errors: yes

- name: prep bucket for future use
  command: aws s3 rm s3://qcentrix.createworkspaces/create-workspaces.csv
  remote_user: ec2-user
  ignore_errors: yes
