---
# tasks file for deployworkspaces

- name: Create workspaces directory if it does not exist
  file:
    path: /home/ec2-user/workspaces
    state: directory
    mode: '0755'

- name: Create bin directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin
    state: directory
    mode: '0755'

- name: Create payload directory if it does not exist
  file:
    path: /home/ec2-user/workspaces/bin/payload
    state: directory
    mode: '0755'

- name: pull csv file from s3-bucket
  command: bash /home/ec2-user/awscli.sh
  #  args:
  #    executable: /bin/bash

- name: pull python script file from role
  copy:
    source: roles/deployworkspaces/files/csvconverter.py
    dest: /home/ec2-user/workspaces/bin/csvconverter.py
    mode: '0777'

- name: pull bash script file from role
  file:
    source: roles/deployworkspaces/files/create-batchworkspaces.sh
    dest: /home/ec2-user/workspaces/bin/create-batchworkspaces.sh
    mode: '0777'

- name: parse csv into json payload(s)
  script: /home/ec2-user/workspaces/bin/csvconverter.py create-workspaces.csv
  args:
    executable: python3

- name: parse csv into json payload(s)
  script: /home/ec2-user/workspaces/bin/create-batchworkspaces.sh

- name: running batch workspaces deploy process
  script: create-batchworkspaces.sh

- name: cleanup of artifacts
  file:
    path: /home/ec2-user/workspaces/
    state: absent
