## Metadata for the Ansible tmpdir role.
##
dependencies: []

galaxy_info:
  author: Michael Klatt
  description: Create a temporary working directory.
  version: 0.2.1
  license: MIT
  min_ansible_version: 2.1.1

  # Should work with just about any *nix, but these are the versions it's been
  # tested with.
  platforms:
    - name: EL
      versions:
        - 7
    - name: MacOSX
      versions:
        - 10.11
    - name: Ubuntu
      versions:
        - trusty  # 14.04

  galaxy_tags:
    - system
    - utility
