## Travis CI configuration for the python3 Ansible role.
##
##  <https://travis-ci.org/mdklatt/ansible-python3-role>
##
language: python

python:
  - "3.6"

branches:
  only:
    - master
    - dev

sudo: false  # use container infrastructure

install:
  - python -m pip install ansible
  - python -m pip install -r tests/requirements.txt

script:
  - ansible --version
  - pytest --verbose tests/test_role.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
